using System.ComponentModel.DataAnnotations;

public class PostDto
{
    [Required]
    /// <summary>
    /// The unique identifier for the blog post, represented as a string.
    /// The value is generated by MongoDB when a new post is created and is stored as a string for easier handling in the application.
    /// Example: "60c72b2f9b1e8a5d6c8f9e7a"
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The username of the author who created the blog post.
    /// </summary>
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>
    ///  The title of the blog post. This is a required field and cannot be empty.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// The main content of the blog post. This is a required field and cannot be empty.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// The date and time when the blog post was created. This is automatically set to the current UTC time when a new post is created.
    /// Example: "2024-06-01T12:00:00Z"
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// The date and time when the blog post was last updated. This is automatically set to the current UTC time whenever the post is modified.
    /// It is nullable because a post may not have been updated after its initial creation.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}
